#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sb_pallets.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sb_pallets")]
	public partial class sb_dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomer_Detail(Customer_Detail instance);
    partial void UpdateCustomer_Detail(Customer_Detail instance);
    partial void DeleteCustomer_Detail(Customer_Detail instance);
    partial void InsertItem_Detail(Item_Detail instance);
    partial void UpdateItem_Detail(Item_Detail instance);
    partial void DeleteItem_Detail(Item_Detail instance);
    partial void InsertPallets_Description(Pallets_Description instance);
    partial void UpdatePallets_Description(Pallets_Description instance);
    partial void DeletePallets_Description(Pallets_Description instance);
    partial void InsertProduction_Order(Production_Order instance);
    partial void UpdateProduction_Order(Production_Order instance);
    partial void DeleteProduction_Order(Production_Order instance);
    partial void InsertPurchased_Order(Purchased_Order instance);
    partial void UpdatePurchased_Order(Purchased_Order instance);
    partial void DeletePurchased_Order(Purchased_Order instance);
    partial void InsertVendor_Detail(Vendor_Detail instance);
    partial void UpdateVendor_Detail(Vendor_Detail instance);
    partial void DeleteVendor_Detail(Vendor_Detail instance);
    #endregion
		
		public sb_dbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["sb_palletsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public sb_dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sb_dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sb_dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sb_dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Customer_Detail> Customer_Details
		{
			get
			{
				return this.GetTable<Customer_Detail>();
			}
		}
		
		public System.Data.Linq.Table<Item_Detail> Item_Details
		{
			get
			{
				return this.GetTable<Item_Detail>();
			}
		}
		
		public System.Data.Linq.Table<Pallets_Description> Pallets_Descriptions
		{
			get
			{
				return this.GetTable<Pallets_Description>();
			}
		}
		
		public System.Data.Linq.Table<Production_Order> Production_Orders
		{
			get
			{
				return this.GetTable<Production_Order>();
			}
		}
		
		public System.Data.Linq.Table<Purchased_Order> Purchased_Orders
		{
			get
			{
				return this.GetTable<Purchased_Order>();
			}
		}
		
		public System.Data.Linq.Table<Vendor_Detail> Vendor_Details
		{
			get
			{
				return this.GetTable<Vendor_Detail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer_Detail")]
	public partial class Customer_Detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _customer_id;
		
		private string _address;
		
		private EntitySet<Production_Order> _Production_Orders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncustomer_idChanging(string value);
    partial void Oncustomer_idChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    #endregion
		
		public Customer_Detail()
		{
			this._Production_Orders = new EntitySet<Production_Order>(new Action<Production_Order>(this.attach_Production_Orders), new Action<Production_Order>(this.detach_Production_Orders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_id", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string customer_id
		{
			get
			{
				return this._customer_id;
			}
			set
			{
				if ((this._customer_id != value))
				{
					this.Oncustomer_idChanging(value);
					this.SendPropertyChanging();
					this._customer_id = value;
					this.SendPropertyChanged("customer_id");
					this.Oncustomer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_Detail_Production_Order", Storage="_Production_Orders", ThisKey="id", OtherKey="customer_id")]
		public EntitySet<Production_Order> Production_Orders
		{
			get
			{
				return this._Production_Orders;
			}
			set
			{
				this._Production_Orders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Production_Orders(Production_Order entity)
		{
			this.SendPropertyChanging();
			entity.Customer_Detail = this;
		}
		
		private void detach_Production_Orders(Production_Order entity)
		{
			this.SendPropertyChanging();
			entity.Customer_Detail = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Item_Detail")]
	public partial class Item_Detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _item_id;
		
		private string _item_description;
		
		private EntitySet<Purchased_Order> _Purchased_Orders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onitem_idChanging(int value);
    partial void Onitem_idChanged();
    partial void Onitem_descriptionChanging(string value);
    partial void Onitem_descriptionChanged();
    #endregion
		
		public Item_Detail()
		{
			this._Purchased_Orders = new EntitySet<Purchased_Order>(new Action<Purchased_Order>(this.attach_Purchased_Orders), new Action<Purchased_Order>(this.detach_Purchased_Orders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int item_id
		{
			get
			{
				return this._item_id;
			}
			set
			{
				if ((this._item_id != value))
				{
					this.Onitem_idChanging(value);
					this.SendPropertyChanging();
					this._item_id = value;
					this.SendPropertyChanged("item_id");
					this.Onitem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_description", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string item_description
		{
			get
			{
				return this._item_description;
			}
			set
			{
				if ((this._item_description != value))
				{
					this.Onitem_descriptionChanging(value);
					this.SendPropertyChanging();
					this._item_description = value;
					this.SendPropertyChanged("item_description");
					this.Onitem_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Item_Detail_Purchased_Order", Storage="_Purchased_Orders", ThisKey="item_id", OtherKey="item_id")]
		public EntitySet<Purchased_Order> Purchased_Orders
		{
			get
			{
				return this._Purchased_Orders;
			}
			set
			{
				this._Purchased_Orders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Purchased_Orders(Purchased_Order entity)
		{
			this.SendPropertyChanging();
			entity.Item_Detail = this;
		}
		
		private void detach_Purchased_Orders(Purchased_Order entity)
		{
			this.SendPropertyChanging();
			entity.Item_Detail = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pallets_Description")]
	public partial class Pallets_Description : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _pallets_id;
		
		private string _description;
		
		private string _image;
		
		private string _comments;
		
		private int _long;
		
		private int _wide;
		
		private string _type;
		
		private string _top_deck;
		
		private string _stringer;
		
		private string _bottom_deck;
		
		private int _top_cut_quantity;
		
		private int _stringer_cut_quantity;
		
		private int _bottome_cut_quantity;
		
		private string _fastner_id;
		
		private decimal _fastner_lenght;
		
		private int _total_nail_each;
		
		private string _lumber_id;
		
		private int _top_wood_quantity;
		
		private int _stringer_wood_quantity;
		
		private int _bottom_wood_quantity;
		
		private string _ht;
		
		private string _stamp;
		
		private string _color;
		
		private string _tight;
		
		private string _wing;
		
		private EntitySet<Production_Order> _Production_Orders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpallets_idChanging(string value);
    partial void Onpallets_idChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OncommentsChanging(string value);
    partial void OncommentsChanged();
    partial void OnlongChanging(int value);
    partial void OnlongChanged();
    partial void OnwideChanging(int value);
    partial void OnwideChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void Ontop_deckChanging(string value);
    partial void Ontop_deckChanged();
    partial void OnstringerChanging(string value);
    partial void OnstringerChanged();
    partial void Onbottom_deckChanging(string value);
    partial void Onbottom_deckChanged();
    partial void Ontop_cut_quantityChanging(int value);
    partial void Ontop_cut_quantityChanged();
    partial void Onstringer_cut_quantityChanging(int value);
    partial void Onstringer_cut_quantityChanged();
    partial void Onbottome_cut_quantityChanging(int value);
    partial void Onbottome_cut_quantityChanged();
    partial void Onfastner_idChanging(string value);
    partial void Onfastner_idChanged();
    partial void Onfastner_lenghtChanging(decimal value);
    partial void Onfastner_lenghtChanged();
    partial void Ontotal_nail_eachChanging(int value);
    partial void Ontotal_nail_eachChanged();
    partial void Onlumber_idChanging(string value);
    partial void Onlumber_idChanged();
    partial void Ontop_wood_quantityChanging(int value);
    partial void Ontop_wood_quantityChanged();
    partial void Onstringer_wood_quantityChanging(int value);
    partial void Onstringer_wood_quantityChanged();
    partial void Onbottom_wood_quantityChanging(int value);
    partial void Onbottom_wood_quantityChanged();
    partial void OnhtChanging(string value);
    partial void OnhtChanged();
    partial void OnstampChanging(string value);
    partial void OnstampChanged();
    partial void OncolorChanging(string value);
    partial void OncolorChanged();
    partial void OntightChanging(string value);
    partial void OntightChanged();
    partial void OnwingChanging(string value);
    partial void OnwingChanged();
    #endregion
		
		public Pallets_Description()
		{
			this._Production_Orders = new EntitySet<Production_Order>(new Action<Production_Order>(this.attach_Production_Orders), new Action<Production_Order>(this.detach_Production_Orders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pallets_id", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string pallets_id
		{
			get
			{
				return this._pallets_id;
			}
			set
			{
				if ((this._pallets_id != value))
				{
					this.Onpallets_idChanging(value);
					this.SendPropertyChanging();
					this._pallets_id = value;
					this.SendPropertyChanged("pallets_id");
					this.Onpallets_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this.OncommentsChanging(value);
					this.SendPropertyChanging();
					this._comments = value;
					this.SendPropertyChanged("comments");
					this.OncommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="long", Storage="_long", DbType="Int NOT NULL")]
		public int @long
		{
			get
			{
				return this._long;
			}
			set
			{
				if ((this._long != value))
				{
					this.OnlongChanging(value);
					this.SendPropertyChanging();
					this._long = value;
					this.SendPropertyChanged("@long");
					this.OnlongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wide", DbType="Int NOT NULL")]
		public int wide
		{
			get
			{
				return this._wide;
			}
			set
			{
				if ((this._wide != value))
				{
					this.OnwideChanging(value);
					this.SendPropertyChanging();
					this._wide = value;
					this.SendPropertyChanged("wide");
					this.OnwideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_top_deck", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string top_deck
		{
			get
			{
				return this._top_deck;
			}
			set
			{
				if ((this._top_deck != value))
				{
					this.Ontop_deckChanging(value);
					this.SendPropertyChanging();
					this._top_deck = value;
					this.SendPropertyChanged("top_deck");
					this.Ontop_deckChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stringer", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string stringer
		{
			get
			{
				return this._stringer;
			}
			set
			{
				if ((this._stringer != value))
				{
					this.OnstringerChanging(value);
					this.SendPropertyChanging();
					this._stringer = value;
					this.SendPropertyChanged("stringer");
					this.OnstringerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bottom_deck", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string bottom_deck
		{
			get
			{
				return this._bottom_deck;
			}
			set
			{
				if ((this._bottom_deck != value))
				{
					this.Onbottom_deckChanging(value);
					this.SendPropertyChanging();
					this._bottom_deck = value;
					this.SendPropertyChanged("bottom_deck");
					this.Onbottom_deckChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_top_cut_quantity", DbType="Int NOT NULL")]
		public int top_cut_quantity
		{
			get
			{
				return this._top_cut_quantity;
			}
			set
			{
				if ((this._top_cut_quantity != value))
				{
					this.Ontop_cut_quantityChanging(value);
					this.SendPropertyChanging();
					this._top_cut_quantity = value;
					this.SendPropertyChanged("top_cut_quantity");
					this.Ontop_cut_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stringer_cut_quantity", DbType="Int NOT NULL")]
		public int stringer_cut_quantity
		{
			get
			{
				return this._stringer_cut_quantity;
			}
			set
			{
				if ((this._stringer_cut_quantity != value))
				{
					this.Onstringer_cut_quantityChanging(value);
					this.SendPropertyChanging();
					this._stringer_cut_quantity = value;
					this.SendPropertyChanged("stringer_cut_quantity");
					this.Onstringer_cut_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bottome_cut_quantity", DbType="Int NOT NULL")]
		public int bottome_cut_quantity
		{
			get
			{
				return this._bottome_cut_quantity;
			}
			set
			{
				if ((this._bottome_cut_quantity != value))
				{
					this.Onbottome_cut_quantityChanging(value);
					this.SendPropertyChanging();
					this._bottome_cut_quantity = value;
					this.SendPropertyChanged("bottome_cut_quantity");
					this.Onbottome_cut_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fastner_id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fastner_id
		{
			get
			{
				return this._fastner_id;
			}
			set
			{
				if ((this._fastner_id != value))
				{
					this.Onfastner_idChanging(value);
					this.SendPropertyChanging();
					this._fastner_id = value;
					this.SendPropertyChanged("fastner_id");
					this.Onfastner_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fastner_lenght", DbType="Decimal(5,2) NOT NULL")]
		public decimal fastner_lenght
		{
			get
			{
				return this._fastner_lenght;
			}
			set
			{
				if ((this._fastner_lenght != value))
				{
					this.Onfastner_lenghtChanging(value);
					this.SendPropertyChanging();
					this._fastner_lenght = value;
					this.SendPropertyChanged("fastner_lenght");
					this.Onfastner_lenghtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_nail_each", DbType="Int NOT NULL")]
		public int total_nail_each
		{
			get
			{
				return this._total_nail_each;
			}
			set
			{
				if ((this._total_nail_each != value))
				{
					this.Ontotal_nail_eachChanging(value);
					this.SendPropertyChanging();
					this._total_nail_each = value;
					this.SendPropertyChanged("total_nail_each");
					this.Ontotal_nail_eachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lumber_id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string lumber_id
		{
			get
			{
				return this._lumber_id;
			}
			set
			{
				if ((this._lumber_id != value))
				{
					this.Onlumber_idChanging(value);
					this.SendPropertyChanging();
					this._lumber_id = value;
					this.SendPropertyChanged("lumber_id");
					this.Onlumber_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_top_wood_quantity", DbType="Int NOT NULL")]
		public int top_wood_quantity
		{
			get
			{
				return this._top_wood_quantity;
			}
			set
			{
				if ((this._top_wood_quantity != value))
				{
					this.Ontop_wood_quantityChanging(value);
					this.SendPropertyChanging();
					this._top_wood_quantity = value;
					this.SendPropertyChanged("top_wood_quantity");
					this.Ontop_wood_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stringer_wood_quantity", DbType="Int NOT NULL")]
		public int stringer_wood_quantity
		{
			get
			{
				return this._stringer_wood_quantity;
			}
			set
			{
				if ((this._stringer_wood_quantity != value))
				{
					this.Onstringer_wood_quantityChanging(value);
					this.SendPropertyChanging();
					this._stringer_wood_quantity = value;
					this.SendPropertyChanged("stringer_wood_quantity");
					this.Onstringer_wood_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bottom_wood_quantity", DbType="Int NOT NULL")]
		public int bottom_wood_quantity
		{
			get
			{
				return this._bottom_wood_quantity;
			}
			set
			{
				if ((this._bottom_wood_quantity != value))
				{
					this.Onbottom_wood_quantityChanging(value);
					this.SendPropertyChanging();
					this._bottom_wood_quantity = value;
					this.SendPropertyChanged("bottom_wood_quantity");
					this.Onbottom_wood_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ht", DbType="VarChar(50)")]
		public string ht
		{
			get
			{
				return this._ht;
			}
			set
			{
				if ((this._ht != value))
				{
					this.OnhtChanging(value);
					this.SendPropertyChanging();
					this._ht = value;
					this.SendPropertyChanged("ht");
					this.OnhtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stamp", DbType="VarChar(50)")]
		public string stamp
		{
			get
			{
				return this._stamp;
			}
			set
			{
				if ((this._stamp != value))
				{
					this.OnstampChanging(value);
					this.SendPropertyChanging();
					this._stamp = value;
					this.SendPropertyChanged("stamp");
					this.OnstampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="VarChar(50)")]
		public string color
		{
			get
			{
				return this._color;
			}
			set
			{
				if ((this._color != value))
				{
					this.OncolorChanging(value);
					this.SendPropertyChanging();
					this._color = value;
					this.SendPropertyChanged("color");
					this.OncolorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tight", DbType="VarChar(50)")]
		public string tight
		{
			get
			{
				return this._tight;
			}
			set
			{
				if ((this._tight != value))
				{
					this.OntightChanging(value);
					this.SendPropertyChanging();
					this._tight = value;
					this.SendPropertyChanged("tight");
					this.OntightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wing", DbType="VarChar(50)")]
		public string wing
		{
			get
			{
				return this._wing;
			}
			set
			{
				if ((this._wing != value))
				{
					this.OnwingChanging(value);
					this.SendPropertyChanging();
					this._wing = value;
					this.SendPropertyChanged("wing");
					this.OnwingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pallets_Description_Production_Order", Storage="_Production_Orders", ThisKey="pallets_id", OtherKey="pallets_id")]
		public EntitySet<Production_Order> Production_Orders
		{
			get
			{
				return this._Production_Orders;
			}
			set
			{
				this._Production_Orders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Production_Orders(Production_Order entity)
		{
			this.SendPropertyChanging();
			entity.Pallets_Description = this;
		}
		
		private void detach_Production_Orders(Production_Order entity)
		{
			this.SendPropertyChanging();
			entity.Pallets_Description = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Production_Order")]
	public partial class Production_Order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _order_id;
		
		private int _customer_id;
		
		private int _order_quantity;
		
		private int _production_quantity;
		
		private int _ship_quantity;
		
		private int _balance_quantity;
		
		private System.DateTime _start_date;
		
		private System.DateTime _due_date;
		
		private System.TimeSpan _start_time;
		
		private System.TimeSpan _end_time;
		
		private int _total_hours;
		
		private string _order_notes;
		
		private string _pallets_id;
		
		private EntityRef<Customer_Detail> _Customer_Detail;
		
		private EntityRef<Pallets_Description> _Pallets_Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onorder_idChanging(int value);
    partial void Onorder_idChanged();
    partial void Oncustomer_idChanging(int value);
    partial void Oncustomer_idChanged();
    partial void Onorder_quantityChanging(int value);
    partial void Onorder_quantityChanged();
    partial void Onproduction_quantityChanging(int value);
    partial void Onproduction_quantityChanged();
    partial void Onship_quantityChanging(int value);
    partial void Onship_quantityChanged();
    partial void Onbalance_quantityChanging(int value);
    partial void Onbalance_quantityChanged();
    partial void Onstart_dateChanging(System.DateTime value);
    partial void Onstart_dateChanged();
    partial void Ondue_dateChanging(System.DateTime value);
    partial void Ondue_dateChanged();
    partial void Onstart_timeChanging(System.TimeSpan value);
    partial void Onstart_timeChanged();
    partial void Onend_timeChanging(System.TimeSpan value);
    partial void Onend_timeChanged();
    partial void Ontotal_hoursChanging(int value);
    partial void Ontotal_hoursChanged();
    partial void Onorder_notesChanging(string value);
    partial void Onorder_notesChanged();
    partial void Onpallets_idChanging(string value);
    partial void Onpallets_idChanged();
    #endregion
		
		public Production_Order()
		{
			this._Customer_Detail = default(EntityRef<Customer_Detail>);
			this._Pallets_Description = default(EntityRef<Pallets_Description>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this.Onorder_idChanging(value);
					this.SendPropertyChanging();
					this._order_id = value;
					this.SendPropertyChanged("order_id");
					this.Onorder_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_id", DbType="Int NOT NULL")]
		public int customer_id
		{
			get
			{
				return this._customer_id;
			}
			set
			{
				if ((this._customer_id != value))
				{
					if (this._Customer_Detail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncustomer_idChanging(value);
					this.SendPropertyChanging();
					this._customer_id = value;
					this.SendPropertyChanged("customer_id");
					this.Oncustomer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_quantity", DbType="Int NOT NULL")]
		public int order_quantity
		{
			get
			{
				return this._order_quantity;
			}
			set
			{
				if ((this._order_quantity != value))
				{
					this.Onorder_quantityChanging(value);
					this.SendPropertyChanging();
					this._order_quantity = value;
					this.SendPropertyChanged("order_quantity");
					this.Onorder_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_production_quantity", DbType="Int NOT NULL")]
		public int production_quantity
		{
			get
			{
				return this._production_quantity;
			}
			set
			{
				if ((this._production_quantity != value))
				{
					this.Onproduction_quantityChanging(value);
					this.SendPropertyChanging();
					this._production_quantity = value;
					this.SendPropertyChanged("production_quantity");
					this.Onproduction_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ship_quantity", DbType="Int NOT NULL")]
		public int ship_quantity
		{
			get
			{
				return this._ship_quantity;
			}
			set
			{
				if ((this._ship_quantity != value))
				{
					this.Onship_quantityChanging(value);
					this.SendPropertyChanging();
					this._ship_quantity = value;
					this.SendPropertyChanged("ship_quantity");
					this.Onship_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance_quantity", DbType="Int NOT NULL")]
		public int balance_quantity
		{
			get
			{
				return this._balance_quantity;
			}
			set
			{
				if ((this._balance_quantity != value))
				{
					this.Onbalance_quantityChanging(value);
					this.SendPropertyChanging();
					this._balance_quantity = value;
					this.SendPropertyChanged("balance_quantity");
					this.Onbalance_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_date", DbType="Date NOT NULL")]
		public System.DateTime start_date
		{
			get
			{
				return this._start_date;
			}
			set
			{
				if ((this._start_date != value))
				{
					this.Onstart_dateChanging(value);
					this.SendPropertyChanging();
					this._start_date = value;
					this.SendPropertyChanged("start_date");
					this.Onstart_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_due_date", DbType="Date NOT NULL")]
		public System.DateTime due_date
		{
			get
			{
				return this._due_date;
			}
			set
			{
				if ((this._due_date != value))
				{
					this.Ondue_dateChanging(value);
					this.SendPropertyChanging();
					this._due_date = value;
					this.SendPropertyChanged("due_date");
					this.Ondue_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_time", DbType="Time NOT NULL")]
		public System.TimeSpan start_time
		{
			get
			{
				return this._start_time;
			}
			set
			{
				if ((this._start_time != value))
				{
					this.Onstart_timeChanging(value);
					this.SendPropertyChanging();
					this._start_time = value;
					this.SendPropertyChanged("start_time");
					this.Onstart_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_time", DbType="Time NOT NULL")]
		public System.TimeSpan end_time
		{
			get
			{
				return this._end_time;
			}
			set
			{
				if ((this._end_time != value))
				{
					this.Onend_timeChanging(value);
					this.SendPropertyChanging();
					this._end_time = value;
					this.SendPropertyChanged("end_time");
					this.Onend_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_hours", DbType="Int NOT NULL")]
		public int total_hours
		{
			get
			{
				return this._total_hours;
			}
			set
			{
				if ((this._total_hours != value))
				{
					this.Ontotal_hoursChanging(value);
					this.SendPropertyChanging();
					this._total_hours = value;
					this.SendPropertyChanged("total_hours");
					this.Ontotal_hoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_notes", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string order_notes
		{
			get
			{
				return this._order_notes;
			}
			set
			{
				if ((this._order_notes != value))
				{
					this.Onorder_notesChanging(value);
					this.SendPropertyChanging();
					this._order_notes = value;
					this.SendPropertyChanged("order_notes");
					this.Onorder_notesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pallets_id", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string pallets_id
		{
			get
			{
				return this._pallets_id;
			}
			set
			{
				if ((this._pallets_id != value))
				{
					if (this._Pallets_Description.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpallets_idChanging(value);
					this.SendPropertyChanging();
					this._pallets_id = value;
					this.SendPropertyChanged("pallets_id");
					this.Onpallets_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_Detail_Production_Order", Storage="_Customer_Detail", ThisKey="customer_id", OtherKey="id", IsForeignKey=true)]
		public Customer_Detail Customer_Detail
		{
			get
			{
				return this._Customer_Detail.Entity;
			}
			set
			{
				Customer_Detail previousValue = this._Customer_Detail.Entity;
				if (((previousValue != value) 
							|| (this._Customer_Detail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Customer_Detail.Entity = null;
						previousValue.Production_Orders.Remove(this);
					}
					this._Customer_Detail.Entity = value;
					if ((value != null))
					{
						value.Production_Orders.Add(this);
						this._customer_id = value.id;
					}
					else
					{
						this._customer_id = default(int);
					}
					this.SendPropertyChanged("Customer_Detail");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pallets_Description_Production_Order", Storage="_Pallets_Description", ThisKey="pallets_id", OtherKey="pallets_id", IsForeignKey=true)]
		public Pallets_Description Pallets_Description
		{
			get
			{
				return this._Pallets_Description.Entity;
			}
			set
			{
				Pallets_Description previousValue = this._Pallets_Description.Entity;
				if (((previousValue != value) 
							|| (this._Pallets_Description.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pallets_Description.Entity = null;
						previousValue.Production_Orders.Remove(this);
					}
					this._Pallets_Description.Entity = value;
					if ((value != null))
					{
						value.Production_Orders.Add(this);
						this._pallets_id = value.pallets_id;
					}
					else
					{
						this._pallets_id = default(string);
					}
					this.SendPropertyChanged("Pallets_Description");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Purchased_Order")]
	public partial class Purchased_Order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _purchase_id;
		
		private int _vendor_id;
		
		private int _item_id;
		
		private System.DateTime _order_date;
		
		private System.DateTime _request_date;
		
		private string _order_by_name;
		
		private string _confirm_by_name;
		
		private int _terms_days;
		
		private bool _ship_via;
		
		private int _order_number;
		
		private int _item_quantity;
		
		private decimal _unit_price;
		
		private decimal _price_fbm;
		
		private decimal _amount;
		
		private EntityRef<Item_Detail> _Item_Detail;
		
		private EntityRef<Vendor_Detail> _Vendor_Detail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpurchase_idChanging(int value);
    partial void Onpurchase_idChanged();
    partial void Onvendor_idChanging(int value);
    partial void Onvendor_idChanged();
    partial void Onitem_idChanging(int value);
    partial void Onitem_idChanged();
    partial void Onorder_dateChanging(System.DateTime value);
    partial void Onorder_dateChanged();
    partial void Onrequest_dateChanging(System.DateTime value);
    partial void Onrequest_dateChanged();
    partial void Onorder_by_nameChanging(string value);
    partial void Onorder_by_nameChanged();
    partial void Onconfirm_by_nameChanging(string value);
    partial void Onconfirm_by_nameChanged();
    partial void Onterms_daysChanging(int value);
    partial void Onterms_daysChanged();
    partial void Onship_viaChanging(bool value);
    partial void Onship_viaChanged();
    partial void Onorder_numberChanging(int value);
    partial void Onorder_numberChanged();
    partial void Onitem_quantityChanging(int value);
    partial void Onitem_quantityChanged();
    partial void Onunit_priceChanging(decimal value);
    partial void Onunit_priceChanged();
    partial void Onprice_fbmChanging(decimal value);
    partial void Onprice_fbmChanged();
    partial void OnamountChanging(decimal value);
    partial void OnamountChanged();
    #endregion
		
		public Purchased_Order()
		{
			this._Item_Detail = default(EntityRef<Item_Detail>);
			this._Vendor_Detail = default(EntityRef<Vendor_Detail>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_purchase_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int purchase_id
		{
			get
			{
				return this._purchase_id;
			}
			set
			{
				if ((this._purchase_id != value))
				{
					this.Onpurchase_idChanging(value);
					this.SendPropertyChanging();
					this._purchase_id = value;
					this.SendPropertyChanged("purchase_id");
					this.Onpurchase_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendor_id", DbType="Int NOT NULL")]
		public int vendor_id
		{
			get
			{
				return this._vendor_id;
			}
			set
			{
				if ((this._vendor_id != value))
				{
					if (this._Vendor_Detail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onvendor_idChanging(value);
					this.SendPropertyChanging();
					this._vendor_id = value;
					this.SendPropertyChanged("vendor_id");
					this.Onvendor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_id", DbType="Int NOT NULL")]
		public int item_id
		{
			get
			{
				return this._item_id;
			}
			set
			{
				if ((this._item_id != value))
				{
					if (this._Item_Detail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onitem_idChanging(value);
					this.SendPropertyChanging();
					this._item_id = value;
					this.SendPropertyChanged("item_id");
					this.Onitem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_date", DbType="Date NOT NULL")]
		public System.DateTime order_date
		{
			get
			{
				return this._order_date;
			}
			set
			{
				if ((this._order_date != value))
				{
					this.Onorder_dateChanging(value);
					this.SendPropertyChanging();
					this._order_date = value;
					this.SendPropertyChanged("order_date");
					this.Onorder_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_request_date", DbType="Date NOT NULL")]
		public System.DateTime request_date
		{
			get
			{
				return this._request_date;
			}
			set
			{
				if ((this._request_date != value))
				{
					this.Onrequest_dateChanging(value);
					this.SendPropertyChanging();
					this._request_date = value;
					this.SendPropertyChanged("request_date");
					this.Onrequest_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_by_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string order_by_name
		{
			get
			{
				return this._order_by_name;
			}
			set
			{
				if ((this._order_by_name != value))
				{
					this.Onorder_by_nameChanging(value);
					this.SendPropertyChanging();
					this._order_by_name = value;
					this.SendPropertyChanged("order_by_name");
					this.Onorder_by_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_confirm_by_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string confirm_by_name
		{
			get
			{
				return this._confirm_by_name;
			}
			set
			{
				if ((this._confirm_by_name != value))
				{
					this.Onconfirm_by_nameChanging(value);
					this.SendPropertyChanging();
					this._confirm_by_name = value;
					this.SendPropertyChanged("confirm_by_name");
					this.Onconfirm_by_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_terms_days", DbType="Int NOT NULL")]
		public int terms_days
		{
			get
			{
				return this._terms_days;
			}
			set
			{
				if ((this._terms_days != value))
				{
					this.Onterms_daysChanging(value);
					this.SendPropertyChanging();
					this._terms_days = value;
					this.SendPropertyChanged("terms_days");
					this.Onterms_daysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ship_via", DbType="Bit NOT NULL")]
		public bool ship_via
		{
			get
			{
				return this._ship_via;
			}
			set
			{
				if ((this._ship_via != value))
				{
					this.Onship_viaChanging(value);
					this.SendPropertyChanging();
					this._ship_via = value;
					this.SendPropertyChanged("ship_via");
					this.Onship_viaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_number", DbType="Int NOT NULL")]
		public int order_number
		{
			get
			{
				return this._order_number;
			}
			set
			{
				if ((this._order_number != value))
				{
					this.Onorder_numberChanging(value);
					this.SendPropertyChanging();
					this._order_number = value;
					this.SendPropertyChanged("order_number");
					this.Onorder_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_quantity", DbType="Int NOT NULL")]
		public int item_quantity
		{
			get
			{
				return this._item_quantity;
			}
			set
			{
				if ((this._item_quantity != value))
				{
					this.Onitem_quantityChanging(value);
					this.SendPropertyChanging();
					this._item_quantity = value;
					this.SendPropertyChanged("item_quantity");
					this.Onitem_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unit_price", DbType="Decimal(10,2) NOT NULL")]
		public decimal unit_price
		{
			get
			{
				return this._unit_price;
			}
			set
			{
				if ((this._unit_price != value))
				{
					this.Onunit_priceChanging(value);
					this.SendPropertyChanging();
					this._unit_price = value;
					this.SendPropertyChanged("unit_price");
					this.Onunit_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_fbm", DbType="Decimal(10,2) NOT NULL")]
		public decimal price_fbm
		{
			get
			{
				return this._price_fbm;
			}
			set
			{
				if ((this._price_fbm != value))
				{
					this.Onprice_fbmChanging(value);
					this.SendPropertyChanging();
					this._price_fbm = value;
					this.SendPropertyChanged("price_fbm");
					this.Onprice_fbmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Decimal(18,2) NOT NULL")]
		public decimal amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				if ((this._amount != value))
				{
					this.OnamountChanging(value);
					this.SendPropertyChanging();
					this._amount = value;
					this.SendPropertyChanged("amount");
					this.OnamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Item_Detail_Purchased_Order", Storage="_Item_Detail", ThisKey="item_id", OtherKey="item_id", IsForeignKey=true)]
		public Item_Detail Item_Detail
		{
			get
			{
				return this._Item_Detail.Entity;
			}
			set
			{
				Item_Detail previousValue = this._Item_Detail.Entity;
				if (((previousValue != value) 
							|| (this._Item_Detail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Item_Detail.Entity = null;
						previousValue.Purchased_Orders.Remove(this);
					}
					this._Item_Detail.Entity = value;
					if ((value != null))
					{
						value.Purchased_Orders.Add(this);
						this._item_id = value.item_id;
					}
					else
					{
						this._item_id = default(int);
					}
					this.SendPropertyChanged("Item_Detail");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vendor_Detail_Purchased_Order", Storage="_Vendor_Detail", ThisKey="vendor_id", OtherKey="vendor_id", IsForeignKey=true)]
		public Vendor_Detail Vendor_Detail
		{
			get
			{
				return this._Vendor_Detail.Entity;
			}
			set
			{
				Vendor_Detail previousValue = this._Vendor_Detail.Entity;
				if (((previousValue != value) 
							|| (this._Vendor_Detail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vendor_Detail.Entity = null;
						previousValue.Purchased_Orders.Remove(this);
					}
					this._Vendor_Detail.Entity = value;
					if ((value != null))
					{
						value.Purchased_Orders.Add(this);
						this._vendor_id = value.vendor_id;
					}
					else
					{
						this._vendor_id = default(int);
					}
					this.SendPropertyChanged("Vendor_Detail");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vendor_Detail")]
	public partial class Vendor_Detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _vendor_id;
		
		private string _vendor_address;
		
		private EntitySet<Purchased_Order> _Purchased_Orders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onvendor_idChanging(int value);
    partial void Onvendor_idChanged();
    partial void Onvendor_addressChanging(string value);
    partial void Onvendor_addressChanged();
    #endregion
		
		public Vendor_Detail()
		{
			this._Purchased_Orders = new EntitySet<Purchased_Order>(new Action<Purchased_Order>(this.attach_Purchased_Orders), new Action<Purchased_Order>(this.detach_Purchased_Orders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendor_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int vendor_id
		{
			get
			{
				return this._vendor_id;
			}
			set
			{
				if ((this._vendor_id != value))
				{
					this.Onvendor_idChanging(value);
					this.SendPropertyChanging();
					this._vendor_id = value;
					this.SendPropertyChanged("vendor_id");
					this.Onvendor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendor_address", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string vendor_address
		{
			get
			{
				return this._vendor_address;
			}
			set
			{
				if ((this._vendor_address != value))
				{
					this.Onvendor_addressChanging(value);
					this.SendPropertyChanging();
					this._vendor_address = value;
					this.SendPropertyChanged("vendor_address");
					this.Onvendor_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vendor_Detail_Purchased_Order", Storage="_Purchased_Orders", ThisKey="vendor_id", OtherKey="vendor_id")]
		public EntitySet<Purchased_Order> Purchased_Orders
		{
			get
			{
				return this._Purchased_Orders;
			}
			set
			{
				this._Purchased_Orders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Purchased_Orders(Purchased_Order entity)
		{
			this.SendPropertyChanging();
			entity.Vendor_Detail = this;
		}
		
		private void detach_Purchased_Orders(Purchased_Order entity)
		{
			this.SendPropertyChanging();
			entity.Vendor_Detail = null;
		}
	}
}
#pragma warning restore 1591
